###
GET http://localhost:30003

###
GET http://localhost:30003/quote?symbol=IBM
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1ODkyNDk2NDYsInVzZXJfaWQiOiJkaWVnb0Bob3RtLmNvbSIsImlhdCI6MTU4OTI0OTUyNn0.yD-pkPLGVSX19CSXyNF0fdXRHW5GjZo_1kP2sT5rHo0

###
GET http://localhost:30003/quote/symbols?symbol=IBM


###
POST http://localhost:30003/users
Content-Type: application/json

{
    "email": "diego@hotm.com",
    "password": "diego1"
}


###
POST http://localhost:30003/users/login
Content-Type: application/json

{
    "email": "diego@hotm.com",
    "password": "diego1"
}
