###
GET http://localhost:30003

###
GET http://localhost:30003/quote?symbol=IBM
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1ODkzMzg1NDgsImVtYWlsIjoidXNlckBleGFtcGxlLmNvbSIsImlhdCI6MTU4OTMzODQyOH0.u63JzeCLX7FiYzA50LGnUgW4k9wcUw8vBEvtN4sbxuU

###
GET http://localhost:30003/quote/symbols?symbol=IBM


###
POST http://localhost:30003/users
Content-Type: application/json

{
    "email": "diego@hotm.com",
    "password": "diego1"
}


###
POST http://localhost:30003/users/login
Content-Type: application/json

{
    "email": "diego@hotm.com",
    "password": "diego1"
}
