###
GET http://localhost:30003

###
GET http://localhost:30003/quote?symbol=IBM
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1ODkzNDExODksImVtYWlsIjoidXNlckBleGFtcGxlLmNvbSIsImlhdCI6MTU4OTM0MTA2OX0.Bp5fmFVtZZvMOk3u6MzSNoFPCJds4sNfKMQdsGrABvM

###
GET http://localhost:30003/quote/symbols?symbol=IBM


###
POST http://localhost:30003/users
Content-Type: application/json

{
    "email": "diego@hotm.com",
    "password": "diego1"
}


###
POST http://localhost:30003/users/login
Content-Type: application/json

{
    "email": "user@example.com",
    "password": "string"
}
